name: Deployment Pipeline

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy only on main branch
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            flyctl deploy --remote-only
          else
            echo "Skipping deployment for non-push events."
          fi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
